name: jules stirling
favicon: null
layout_spectrum: 0.73507
typography_spectrum: 0.39033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#656565'
    - '#a6d3a0'
    - '#00bfbf'
    - '#a8a8a8'
    - '#098c93'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
