name: jules stirling
favicon: null
layout_spectrum: 0.73507
typography_spectrum: 0.39033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ececee'
    - '#8f867f'
    - '#4e4e50'
    - '#c7c7c9'
    - '#0e0a07'
  brandStrength: 0.125
  lightness: 0.24004877638071775
  saturation: 0.5
  rhythmicContrast: 0.6993880737572908
purpose: []
